apiVersion: v1
kind: ConfigMap
metadata:
  name: prom-server-config
  labels:
    env: prom-metrics
data:
 prometheus.yml: |-
  global:
    scrape_interval: 15s
    evaluation_interval: 15s
  alerting:
    alertmanagers:
    - static_configs:
      - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
  scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: ['localhost:9090']
      
  - job_name: node1
    static_configs:
    - targets: ['192.168.99.102:9100']
      
 
    
