apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-storage-pvc
  labels:
    env: prom-pvc
spec:
  accessModes:
   - ReadWriteMany
  resources:  
    requests:
      storage: 2Gi



    
