apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deploy
  labels:
    env: prom-metrics
    
spec:
  selector:
    matchLabels:
      env: prom-metrics
      
  replicas: 1
  template:
    metadata:
      name: prometheus-pod
      labels:
        env: prom-metrics
        
    spec:
      containers:
      - name: prometheus-container
        image: vimal13/prometheus
        volumeMounts:
        - name: prom-config-volume
          mountPath: /etc/prometheus/
        - name: prom-storage-volume
          mountPath: /prometheus/
      volumes:
      - name: prom-config-volume
        configMap:
          name: prom-server-config
      - name: prom-storage-volume
        persistentVolumeClaim:
          claimName: prom-storage-pvc
      