apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  labels:
    env: grafana
    
spec:
  selector:
    matchLabels:
      env: grafana
      
  replicas: 1
  template:
    metadata:
      name: grafana-pod
      labels:
        env: grafana
        
    spec:
      containers:
      - name: grafana-container
        image: vimal13/grafana
        volumeMounts:
        - name: grafana-storage-volume
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-storage-volume
        persistentVolumeClaim:
          claimName: grafana-pvc