apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    env: grafana
    
spec:
  selector:
    env: grafana
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000 
    nodePort: 32000