apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  labels:
    env: grafana-pvc1
    
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi 